Library
RunestoneInteractive/RunestoneServer pull request #1716
Opened 2021-07-26 19:45 UTC by qasema

fix issue #1715: 
 
Reorganized Runestone Library, add titles and descriptions to the books, add search bar. 

@bnmnetp each conf.py should include two variable named : _course_description_   and _key_words_ . for example:

course_description = " description ......."
key_words = " fopp21 Brad Miller fall_21 name_college ....."

2021-07-29 15:31 UTC, bnmnetp requested changes
If black is still causing you trouble it may be that you need the version that matches our unit tests.  That is version 20.8b1. You can run black --version to see which one you have.

2021-07-29 15:31 UTC, bnmnetp commented on models/grouped_assignments.py
> -        "points", "integer", default=0, notnull=True
This needs to be put back.  I can walk you through updating your database so it won't cause you problems.

2021-07-29 16:57 UTC, qasema commented
sorry! the last two commits are: fix  black_format_check &  fix group_assignments.py (some typo)

2021-07-30 20:06 UTC, bnmnetp approved these changes

2021-07-30 21:00 UTC, merged